# Taken directly from the nav2_bringup/params/nav2_params.yaml file
# amcl:
#   ros__parameters:
#     alpha1: 0.2
#     alpha2: 0.2
#     alpha3: 0.2
#     alpha4: 0.2
#     alpha5: 0.2
#     base_frame_id: "base_link"
#     beam_skip_distance: 0.5
#     beam_skip_error_threshold: 0.9
#     beam_skip_threshold: 0.3
#     do_beamskip: true
#     global_frame_id: "map"
#     lambda_short: 0.1
#     laser_likelihood_max_dist: 2.0
#     laser_max_range: 100.0
#     laser_min_range: -1.0
#     laser_model_type: "likelihood_field"
#     max_beams: 60
#     max_particles: 2000
#     min_particles: 500
#     odom_frame_id: "odom"
#     pf_err: 0.05
#     pf_z: 0.99
#     recovery_alpha_fast: 0.0
#     recovery_alpha_slow: 0.0
#     resample_interval: 1
#     robot_model_type: "nav2_amcl::DifferentialMotionModel"
#     save_pose_rate: 0.5
#     sigma_hit: 0.2
#     tf_broadcast: true
#     transform_tolerance: 1.0
#     service_introspection_mode: "disabled"
#     update_min_a: 0.2
#     update_min_d: 0.25
#     z_hit: 0.5
#     z_max: 0.05
#     z_rand: 0.5
#     z_short: 0.05
#     scan_topic: scan

# More fine-tuned params
amcl:
  ros__parameters:
    # ODOMETRY MODEL NOISE (alpha*)
    alpha1: 0.05   # rotation noise due to rotation (was 0.2)
    alpha2: 0.05   # translation noise due to translation (was 0.2)
    alpha3: 0.05   # translation noise due to rotation (was 0.2)
    alpha4: 0.05   # rotation noise due to translation (was 0.2)
    alpha5: 0.01   # short-term noise from unexpected behavior (keep low)

    # LASER MODEL
    laser_model_type: "likelihood_field"
    max_beams: 90                      # use more beams for higher accuracy (was 60)
    laser_max_range: 12.0             # realistic lidar range (was 100.0)
    laser_min_range: 0.1              # lidar-specific (was -1.0, which is invalid)
    laser_likelihood_max_dist: 2.0    # max distance at which obstacle affects likelihood
    sigma_hit: 0.2                    # beam noise std dev
    z_hit: 0.8                        # weight for matching beam
    z_rand: 0.15                      # weight for random measurements
    z_short: 0.05                     # short readings weight
    z_max: 0.0                        # disable max range outliers if lidar is clean

    # BEAM SKIPPING (for dynamic environments)
    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    # PARTICLE FILTER
    min_particles: 500
    max_particles: 2000
    resample_interval: 1
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

    # UPDATE THRESHOLDS
    update_min_d: 0.15    # lower = more frequent update (was 0.25)
    update_min_a: 0.1     # more responsive angular update (was 0.2)

    # COORDINATE FRAMES
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"

    # TF + POSE BROADCASTING
    tf_broadcast: true
    transform_tolerance: 0.2         # reduce latency artifacts (was 1.0)
    save_pose_rate: 0.5

    # OTHER
    lambda_short: 0.1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    scan_topic: "scan"
    service_introspection_mode: "disabled"
