amcl:
  ros__parameters:
    alpha1: 0.05   
    alpha2: 0.05   
    alpha3: 0.05   
    alpha4: 0.05   
    alpha5: 0.01   
    laser_model_type: "likelihood_field"
    max_beams: 90                     
    laser_max_range: 12.0             
    laser_min_range: 0.1              
    laser_likelihood_max_dist: 2.0    
    sigma_hit: 0.2                    
    z_hit: 0.8                        
    z_rand: 0.15                      
    z_short: 0.05                     
    z_max: 0.0                        
    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9
    min_particles: 500
    max_particles: 2000
    resample_interval: 1
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    update_min_d: 0.15
    update_min_a: 0.1
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    tf_broadcast: true
    transform_tolerance: 0.2
    save_pose_rate: 0.5
    lambda_short: 0.1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    scan_topic: "scan"
    service_introspection_mode: "disabled"
