waypoints:
  - pose:
      header:
        frame_id: "map"
      pose:
        position:
          x: 2.2
          y: 2.2
          z: 0.0
        orientation:
          z: 0.0
          w: 1.0
  - pose:
      header:
        frame_id: "map"
      pose:
        position:
          x: -1.2
          y: 3.0
          z: 0.0
        orientation:
          z: 0.707
          w: 0.707
  - pose:
      header:
        frame_id: "map"
      pose:
        position:
          x: 2.2
          y: -2.2
          z: 0.0
        orientation:
          z: 1.0
          w: 0.0
  - pose:
      header:
        frame_id: "map"
      pose:
        position:
          x: -2.8
          y: -2.2
          z: 0.0
        orientation:
          z: 0.0
          w: 1.0

charging:
  - pose:
      header:
        frame_id: "map"
      pose:
        position:
          x: -3.5
          y: 0.0
          z: 0.0
        orientation:
          z: 0.0
          w: 1.0